<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<style>

body{
    font-family: DejaVu Sans, sans-serif;
    color:#333;
}

/* Header */
.header{
    text-align:center;
    margin-bottom:20px;
}

.header h1{
    margin:0;
    font-size:28px;
    color:#2563eb;
}

.tagline{
    font-size:12px;
    color:#777;
}

/* Summary */
.summary{
    background:#f3f4f6;
    padding:15px;
    border-radius:5px;
    margin-bottom:20px;
}

/* Cards */
.card{
    border:1px solid #ddd;
    padding:15px;
    margin-bottom:15px;
    border-radius:5px;
}

/* Labels */
.label{
    font-weight:bold;
}

/* Footer */
.footer{
    text-align:center;
    font-size:10px;
    margin-top:30px;
    color:#999;
}

</style>

</head>

<body>

<!-- Header -->
<div class="header">
    <h1>SkillMentor</h1>
    <p class="tagline">Empowering Careers Through Mock Interviews</p>
</div>

<!-- Candidate Info -->
<p><strong>Candidate:</strong> {{ auth()->user()->name }}</p>
<p><strong>Date:</strong> {{ now()->format('d M Y') }}</p>

@php
$ratings = $interviews->pluck('feedback.rating')->filter();
$avg = $ratings->count() ? round($ratings->avg(),1) : 0;
@endphp

<!-- Summary -->
<div class="summary">
    <p><strong>Average Rating:</strong> ⭐ {{ $avg }}/5</p>
    <p><strong>Total Interviews:</strong> {{ $interviews->count() }}</p>
</div>

<!-- Feedback List -->
@foreach($interviews as $interview)

@if($interview->feedback)

<div class="card">

    <p><span class="label">Mentor:</span> {{ $interview->mentor->user->name }}</p>

    <p><span class="label">Date:</span> {{ $interview->slot->date }}</p>

    <p><span class="label">Rating:</span> ⭐ {{ $interview->feedback->rating }}/5</p>

    <p><span class="label">Feedback:</span> {{ $interview->feedback->comments }}</p>

</div>

@endif

@endforeach

<!-- Footer -->
<div class="footer">
    <p>Generated by SkillMentor Platform</p>
</div>

</body>
</html>